import { Router } from "express";
import type pg from "pg";
import { z } from "zod";
import { generateDeviceToken, hashDeviceToken } from "./auth.js";
const createSchema = z.object({ label: z.string().trim().min(1).max(120) });
interface DeviceRow { id: string; label: string; created_at: Date; last_seen_at: Date | null; revoked_at: Date | null }
export function devicesRouter(pool: pg.Pool, pepper: string): Router {
  const router = Router();
  router.get("/", async (req, res, next) => { try { const d=req.device!; const result=await pool.query<DeviceRow>("SELECT id,label,created_at,last_seen_at,revoked_at FROM devices WHERE user_id=$1 AND vault_id=$2 ORDER BY created_at",[d.accountId,d.vaultId]); res.json({devices:result.rows.map((r)=>({id:r.id,label:r.label,createdAt:r.created_at,lastSeenAt:r.last_seen_at,revokedAt:r.revoked_at}))}); } catch(e){next(e);} });
  router.post("/", async (req,res,next)=>{ const parsed=createSchema.safeParse(req.body); if(!parsed.success)return void res.status(400).json({error:"invalid_request",issues:parsed.error.issues}); const d=req.device!; const token=generateDeviceToken(); const hash=hashDeviceToken(token,pepper); const client=await pool.connect(); try{await client.query("BEGIN"); const actor=await client.query("SELECT 1 FROM devices WHERE id=$1 AND revoked_at IS NULL FOR UPDATE",[d.deviceId]); if(!actor.rowCount){await client.query("ROLLBACK");return void res.status(401).json({error:"unauthorized"});} const created=await client.query<{id:string}>("INSERT INTO devices(user_id,vault_id,label,token_fingerprint,token_hash) VALUES ($1,$2,$3,$4,$5) RETURNING id",[d.accountId,d.vaultId,parsed.data.label,hash.subarray(0,16),hash]); await client.query("INSERT INTO audit_events(user_id,vault_id,device_id,event_type) VALUES ($1,$2,$3,'device_created')",[d.accountId,d.vaultId,d.deviceId]); await client.query("COMMIT"); res.status(201).json({deviceId:created.rows[0]!.id,token});}catch(e){await client.query("ROLLBACK").catch(()=>undefined);next(e);}finally{client.release();} });
  router.delete("/:deviceId", async(req,res,next)=>{const target=z.uuid().safeParse(req.params.deviceId);if(!target.success)return void res.status(400).json({error:"invalid_device_id"});const d=req.device!;const client=await pool.connect();try{await client.query("BEGIN");const result=await client.query("UPDATE devices SET revoked_at=COALESCE(revoked_at,now()) WHERE id=$1 AND user_id=$2 AND vault_id=$3 RETURNING id",[target.data,d.accountId,d.vaultId]);if(!result.rowCount){await client.query("ROLLBACK");return void res.status(404).json({error:"device_not_found"});}await client.query("INSERT INTO audit_events(user_id,vault_id,device_id,event_type) VALUES ($1,$2,$3,'device_revoked')",[d.accountId,d.vaultId,d.deviceId]);await client.query("COMMIT");res.status(204).end();}catch(e){await client.query("ROLLBACK").catch(()=>undefined);next(e);}finally{client.release();}});
  return router;
}
